services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: Africa/Johannesburg
      FTLCONF_webserver_api_password: ChangeMe123
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    volumes:
      - ./data/pihole/etc-pihole:/etc/pihole
      - ./data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Africa/Johannesburg
    ports:
      - "8083:80"
    volumes:
      - ./data/heimdall:/config

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - TZ=Africa/Johannesburg
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Africa/Johannesburg
      WEBUI_PORT: 8081
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/downloads:/downloads

  pyload:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/pyload:/config
      - ./data/downloads:/downloads

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8082:8080"

  rustdesk-hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    command: hbbs
    restart: unless-stopped
    volumes:
      - ./data/rustdesk:/data
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"

  rustdesk-hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbr
    restart: unless-stopped
    depends_on:
      - rustdesk-hbbs
    volumes:
      - ./data/rustdesk:/data
    ports:
      - "21117:21117"
      - "21119:21119"

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./data/uptime-kuma:/app/data
